<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

<br>

**4. Create a tensor "x" from the array above**

<br>

**5. Change the dtype of x from `int32` to `int64`**

<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

<br>

**7. Return the right-hand column of tensor `x`**

<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

<br>

**10. Find the matrix product of `x` and `y`.**

</div>

In [1]:
%pip install torch torchvision torchaudio

In [2]:
import torch
import numpy as np

In [3]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

In [4]:
set_seed(42)

arr = np.random.randint(0, 5, 6).astype('int32')

print(arr)
print(arr.dtype)

[3 4 2 4 4 1]
int32


In [5]:
x = torch.from_numpy(arr)

print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [6]:
x = x.type(torch.int64)

print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


In [7]:
x = x.reshape(3, 2)

print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [8]:
right_column = x[:, 1]

print(right_column)

tensor([4, 4, 1])


In [9]:
square_x = x ** 2

print(square_x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [10]:
torch.manual_seed(42)

y = torch.randint(0, 5, (2, 3))

print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [11]:
result = torch.matmul(x, y)

print(result)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


# Conclusion:
This task showed how tensors can be created and changed using PyTorch. The tensor was converted from a NumPy array, its data type was changed, and its shape was modified. Different operations such as getting a column, squaring the values, and matrix multiplication were also performed. This helped demonstrate the basic operations that can be done with PyTorch tensors.